# Generated by Django 5.0.6 on 2024-06-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food_consumer',
            new_name='food_consumed',
        ),
    ]
